version: "3.8"

services:
  justwatch-app:
    image: just-watch-clone
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_API_KEY_TMDB=${NEXT_PUBLIC_API_KEY_TMDB}
