import type { Metadata } from "next";
import { FavoritesProvider } from "@/context/FavoriteContext";
import NavigationBar from "./(components)/NavigationBar";
import { Suspense } from "react";
import { ExpandedStateProvider } from "@/context/ExpandendStateContext";
import { FilterProvider } from "@/context/FilterContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "JustWatch - The Streaming Guide",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Suspense>
          <FavoritesProvider>
            <FilterProvider>
              <ExpandedStateProvider>
                <NavigationBar />
                {children}
              </ExpandedStateProvider>
            </FilterProvider>
          </FavoritesProvider>
        </Suspense>
      </body>
    </html>
  );
}
